<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.bakhtiiartashbolotov</groupId>
    <artifactId>dbeaver-monaco-editor</artifactId>
    <version>${revision}</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>io.github.bakhtiiartashbolotov.dbeaver.monaco.repository</artifactId>
  <packaging>eclipse-repository</packaging>
  <dependencies>
    <dependency>
      <groupId>io.github.bakhtiiartashbolotov</groupId>
      <artifactId>io.github.bakhtiiartashbolotov.dbeaver.monaco.feature</artifactId>
      <version>${revision}</version>
      <type>eclipse-feature</type>
    </dependency>
  </dependencies>
</project>
