<?xml version="1.0"?><project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>io.github.bakhtiiartashbolotov</groupId><artifactId>dbeaver-monaco-editor</artifactId><version>${revision}</version><relativePath>../../pom.xml</relativePath></parent><artifactId>io.github.bakhtiiartashbolotov.dbeaver.monaco.core.tests</artifactId><packaging>eclipse-test-plugin</packaging><build><plugins><plugin><groupId>org.eclipse.tycho</groupId><artifactId>target-platform-configuration</artifactId><version>${tycho.version}</version><configuration><target><artifact><groupId>io.github.bakhtiiartashbolotov</groupId><artifactId>io.github.bakhtiiartashbolotov.dbeaver.monaco.test.target</artifactId><version>${revision}</version></artifact></target></configuration></plugin><plugin><groupId>org.eclipse.tycho</groupId><artifactId>tycho-surefire-plugin</artifactId><version>${tycho.version}</version></plugin></plugins></build></project>
